// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test1() {
    // Test name: Test 1
    // Step # | name | target | value
    // 1 | open | /solium/servlet/userLogin.do | 
    driver.get("https://sum-qa02.shareworks.com/solium/servlet/userLogin.do");
    // 2 | setWindowSize | 1554x1046 | 
    driver.manage().window().setSize(new Dimension(1554, 1046));
    // 3 | click | css=#submit-box > input | 
    driver.findElement(By.cssSelector("#submit-box > input")).click();
    // 4 | click | id=account_number_input | 
    driver.findElement(By.id("account_number_input")).click();
    // 5 | sendKeys | id=account_number_input | ${KEY_ENTER}
    driver.findElement(By.id("account_number_input")).sendKeys(Keys.ENTER);
    // 6 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 7 | sendKeys | id=password | ${KEY_ENTER}
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    // 8 | click | css=#submit-box > input | 
    driver.findElement(By.cssSelector("#submit-box > input")).click();
    // 9 | click | css=#submit-box > input | 
    driver.findElement(By.cssSelector("#submit-box > input")).click();
    // 10 | click | id=nav_tools | 
    driver.findElement(By.id("nav_tools")).click();
    // 11 | click | id=nav_fund | 
    driver.findElement(By.id("nav_fund")).click();
    // 12 | click | id=company_input_id | 
    driver.findElement(By.id("company_input_id")).click();
    // 13 | type | id=company_input_id | Google
    driver.findElement(By.id("company_input_id")).sendKeys("Google");
    // 14 | click | css=.form-button-bar > input | 
    driver.findElement(By.cssSelector(".form-button-bar > input")).click();
    // 15 | click | linkText=Class A - GOOGL - NASDAQ | 
    driver.findElement(By.linkText("Class A - GOOGL - NASDAQ")).click();
    // 16 | click | linkText=Manage Dividends/Distributions | 
    driver.findElement(By.linkText("Manage Dividends/Distributions")).click();
    // 17 | click | linkText=Add Dividend/Distribution | 
    driver.findElement(By.linkText("Add Dividend/Distribution")).click();
    // 18 | click | css=tr:nth-child(7) .ui-datepicker-trigger | 
    driver.findElement(By.cssSelector("tr:nth-child(7) .ui-datepicker-trigger")).click();
    // 19 | click | linkText=22 | 
    driver.findElement(By.linkText("22")).click();
    // 20 | click | css=#normal_record_date .ui-datepicker-trigger | 
    driver.findElement(By.cssSelector("#normal_record_date .ui-datepicker-trigger")).click();
    // 21 | click | linkText=22 | 
    driver.findElement(By.linkText("22")).click();
    // 22 | click | css=tr:nth-child(12) .ui-datepicker-trigger | 
    driver.findElement(By.cssSelector("tr:nth-child(12) .ui-datepicker-trigger")).click();
    // 23 | click | linkText=25 | 
    driver.findElement(By.linkText("25")).click();
    // 24 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 25 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 26 | click | css=tr:nth-child(10) a | 
    driver.findElement(By.cssSelector("tr:nth-child(10) a")).click();
    // 27 | click | linkText=Edit | 
    vars.put("window_handles", driver.getWindowHandles());
    // 28 | storeWindowHandle | root | 
    driver.findElement(By.linkText("Edit")).click();
    // 29 | selectWindow | handle=${win3227} | 
    vars.put("win3227", waitForWindow(2000));
    // 30 | click | id=autofocus | 
    vars.put("root", driver.getWindowHandle());
    // 31 | type | id=autofocus | 0.02
    driver.switchTo().window(vars.get("win3227").toString());
    // 32 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.findElement(By.id("autofocus")).click();
    // 33 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.findElement(By.id("autofocus")).sendKeys("0.02");
    // 34 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 35 | close |  | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 36 | selectWindow | handle=${root} | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 37 | click | css=.form-button-bar > input:nth-child(3) | 
    driver.close();
    // 38 | click | id=nav_tools | 
    driver.switchTo().window(vars.get("root").toString());
    // 39 | click | linkText=Search for Transaction | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(3)")).click();
    // 40 | click | name=companyID | 
    driver.findElement(By.id("nav_tools")).click();
    // 41 | select | name=companyID | label=G & M 401(K) PLAN
    driver.findElement(By.linkText("Search for Transaction")).click();
    // 42 | select | name=companyID | label=goBalto, Inc.(ACQUIRED)-NLFR
    driver.findElement(By.name("companyID")).click();
    // 43 | select | name=companyID | label=Good Human Community Inc.
    {
      WebElement dropdown = driver.findElement(By.name("companyID"));
      dropdown.findElement(By.xpath("//option[. = 'G & M 401(K) PLAN']")).click();
    }
    // 44 | click | name=companyID | 
    {
      WebElement dropdown = driver.findElement(By.name("companyID"));
      dropdown.findElement(By.xpath("//option[. = 'goBalto, Inc.(ACQUIRED)-NLFR']")).click();
    }
    // 45 | click | name=companyID | 
    {
      WebElement dropdown = driver.findElement(By.name("companyID"));
      dropdown.findElement(By.xpath("//option[. = 'Good Human Community Inc.']")).click();
    }
    // 46 | select | name=companyID | label=Google
    driver.findElement(By.name("companyID")).click();
    // 47 | click | name=sponsorPlanID | 
    driver.findElement(By.name("companyID")).click();
    // 48 | select | name=sponsorPlanID | label=Hong Long Share Holding Account
    {
      WebElement dropdown = driver.findElement(By.name("companyID"));
      dropdown.findElement(By.xpath("//option[. = 'Google']")).click();
    }
    // 49 | click | name=savingsPlanID | 
    driver.findElement(By.name("sponsorPlanID")).click();
    // 50 | click | name=savingsPlanID | 
    {
      WebElement dropdown = driver.findElement(By.name("sponsorPlanID"));
      dropdown.findElement(By.xpath("//option[. = 'Hong Long Share Holding Account']")).click();
    }
    // 51 | select | name=savingsPlanID | label=Hong Long Share Savings Plan
    driver.findElement(By.name("savingsPlanID")).click();
    // 52 | click | name=fundID | 
    driver.findElement(By.name("savingsPlanID")).click();
    // 53 | select | name=fundID | label=Class C - GOOG - NASDAQ
    {
      WebElement dropdown = driver.findElement(By.name("savingsPlanID"));
      dropdown.findElement(By.xpath("//option[. = 'Hong Long Share Savings Plan']")).click();
    }
    // 54 | click | name=fundID | 
    driver.findElement(By.name("fundID")).click();
    // 55 | click | name=savingsPlanFundID | 
    {
      WebElement dropdown = driver.findElement(By.name("fundID"));
      dropdown.findElement(By.xpath("//option[. = 'Class C - GOOG - NASDAQ']")).click();
    }
    // 56 | click | name=sponsorPlanID | 
    driver.findElement(By.name("fundID")).click();
    // 57 | click | name=fundID | 
    driver.findElement(By.name("savingsPlanFundID")).click();
    // 58 | click | name=action | 
    driver.findElement(By.name("sponsorPlanID")).click();
    // 59 | click | name=sponsorPlanID | 
    driver.findElement(By.name("fundID")).click();
    // 60 | click | name=fundID | 
    driver.findElement(By.name("action")).click();
    // 61 | select | name=fundID | label=
    driver.findElement(By.name("sponsorPlanID")).click();
    // 62 | click | name=savingsPlanID | 
    driver.findElement(By.name("fundID")).click();
    // 63 | select | name=savingsPlanID | label=
    {
      WebElement dropdown = driver.findElement(By.name("fundID"));
      dropdown.findElement(By.xpath("//option[. = 'label']")).click();
    }
    // 64 | click | name=action | 
    driver.findElement(By.name("savingsPlanID")).click();
    // 65 | click | name=sponsorPlanID | 
    {
      WebElement dropdown = driver.findElement(By.name("savingsPlanID"));
      dropdown.findElement(By.xpath("//option[. = 'label']")).click();
    }
    // 66 | select | name=sponsorPlanID | label=Hong Purchase Plan
    driver.findElement(By.name("action")).click();
    // 67 | click | name=savingsPlanID | 
    driver.findElement(By.name("sponsorPlanID")).click();
    // 68 | click | name=savingsPlanID | 
    {
      WebElement dropdown = driver.findElement(By.name("sponsorPlanID"));
      dropdown.findElement(By.xpath("//option[. = 'Hong Purchase Plan']")).click();
    }
    // 69 | select | name=savingsPlanID | label=Hong Saving Plan
    driver.findElement(By.name("savingsPlanID")).click();
    // 70 | click | name=fundID | 
    driver.findElement(By.name("savingsPlanID")).click();
    // 71 | click | name=fundID | 
    {
      WebElement dropdown = driver.findElement(By.name("savingsPlanID"));
      dropdown.findElement(By.xpath("//option[. = 'Hong Saving Plan']")).click();
    }
    // 72 | select | name=fundID | label=Class A - GOOGL - NASDAQ
    driver.findElement(By.name("fundID")).click();
    // 73 | click | name=savingsPlanFundID | 
    driver.findElement(By.name("fundID")).click();
    // 74 | select | name=savingsPlanFundID | label=Hong Saving Plan - Class A - GOOGL - NASDAQ
    {
      WebElement dropdown = driver.findElement(By.name("fundID"));
      dropdown.findElement(By.xpath("//option[. = 'Class A - GOOGL - NASDAQ']")).click();
    }
    // 75 | click | name=action | 
    driver.findElement(By.name("savingsPlanFundID")).click();
    // 76 | click | linkText=SPLIT | 
    {
      WebElement dropdown = driver.findElement(By.name("savingsPlanFundID"));
      dropdown.findElement(By.xpath("//option[. = 'Hong Saving Plan - Class A - GOOGL - NASDAQ']")).click();
    }
    // 77 | selectWindow | handle=${win7888} | 
    driver.findElement(By.name("action")).click();
    // 78 | click | css=.form-button-bar > input:nth-child(1) | 
    vars.put("window_handles", driver.getWindowHandles());
    // 79 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.findElement(By.linkText("SPLIT")).click();
    // 80 | click | css=input | 
    vars.put("win7888", waitForWindow(2000));
    // 81 | close |  | 
    driver.switchTo().window(vars.get("win7888").toString());
    // 82 | selectWindow | handle=${root} | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 83 | click | linkText=ADJUST | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 84 | selectWindow | handle=${win130} | 
    driver.findElement(By.cssSelector("input")).click();
    // 85 | click | css=tr:nth-child(10) input | 
    driver.close();
    // 86 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.switchTo().window(vars.get("root").toString());
    // 87 | click | css=.form-button-bar > input:nth-child(1) | 
    vars.put("window_handles", driver.getWindowHandles());
    // 88 | click | css=.form-button-bar > input:nth-child(1) | 
    driver.findElement(By.linkText("ADJUST")).click();
    // 89 | click | css=input | 
    vars.put("win130", waitForWindow(2000));
    // 90 | close |  | 
    driver.switchTo().window(vars.get("win130").toString());
    // 91 | selectWindow | handle=${root} | 
    driver.findElement(By.cssSelector("tr:nth-child(10) input")).click();
    // 92 | click | id=nav_user | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 93 | type | id=search_value | qacs2
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 94 | click | id=search | 
    driver.findElement(By.cssSelector(".form-button-bar > input:nth-child(1)")).click();
    // 95 | click | linkText=QA, CS2 | 
    driver.findElement(By.cssSelector("input")).click();
    // 96 | click | linkText=View Statement | 
    driver.close();
    // 97 | click | id=submit_html | 
    driver.switchTo().window(vars.get("root").toString());
    // 98 | click | id=main-wrapper | 
    driver.findElement(By.id("nav_user")).click();
    // 99 | click | css=tr:nth-child(19) a | 
    driver.findElement(By.id("search_value")).sendKeys("qacs2");
    // 100 | selectWindow | handle=${win2698} | 
    driver.findElement(By.id("search")).click();
    // 101 | close |  | 
    driver.findElement(By.linkText("QA, CS2")).click();
    // 102 | selectWindow | handle=${root} | 
    driver.findElement(By.linkText("View Statement")).click();
    // 103 | click | css=.sidemenu-category:nth-child(7) > a:nth-child(3) | 
    driver.findElement(By.id("submit_html")).click();
    // 104 | click | linkText=Manage Tax Certification | 
    driver.findElement(By.id("main-wrapper")).click();
    // 105 | click | id=gwt-debug-decertifyId | 
    vars.put("window_handles", driver.getWindowHandles());
    // 106 | click | css=.gwt-ListBox | 
    driver.findElement(By.cssSelector("tr:nth-child(19) a")).click();
    // 107 | select | css=.gwt-ListBox | label=Name mismatch
    vars.put("win2698", waitForWindow(2000));
    // 108 | click | id=gwt-debug-panelVerifyButton | 
    driver.switchTo().window(vars.get("win2698").toString());
    // 109 | click | id=gwt-debug-panelSubmitButton | 
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".sidemenu-category:nth-child(7) > a:nth-child(3)")).click();
    driver.findElement(By.linkText("Manage Tax Certification")).click();
    driver.findElement(By.id("gwt-debug-decertifyId")).click();
    driver.findElement(By.cssSelector(".gwt-ListBox")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".gwt-ListBox"));
      dropdown.findElement(By.xpath("//option[. = 'Name mismatch']")).click();
    }
    driver.findElement(By.id("gwt-debug-panelVerifyButton")).click();
    driver.findElement(By.id("gwt-debug-panelSubmitButton")).click();
  }
}
