// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class WithdrawalTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","/Users/hong.lu/chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterAll
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void withdrawal() throws InterruptedException {
        // Test name: Withdrawal
        // Step # | name | target | value
        // 1 | open | /solium/servlet/userLogin.do |
        driver.get("http://localhost:7001/solium/servlet/userLogin.do");
        // 2 | setWindowSize | 1211x879 |
        driver.manage().window().setSize(new Dimension(1211, 879));
        // 3 | click | id=account_number_input |
        driver.findElement(By.id("account_number_input")).sendKeys("SA12345678");
        //driver.findElement(By.id("account_number_input")).click();
        // 4 | click | id=password |
        driver.findElement(By.id("password")).sendKeys("q1w2e3r4");
        // 5 | click | css=#submit-box > input |
        driver.findElement(By.cssSelector("#submit-box > input")).click();
        // 6 | type | id=search_value | CS00057592
        driver.findElement(By.id("search_value")).sendKeys("CS00057592");
        // 7 | click | id=search |
        driver.findElement(By.id("search")).click();
        // 8 | click | linkText=HARPER, DOERING |
        driver.findElement(By.linkText("HARPER, DOERING")).click();
        // 9 | click | linkText=Withdraw |
//        try {
//            driver.wait(3);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
        //driver.findElement(By.linkText("Withdraw")).click();
        // 10 | runScript | window.scrollTo(0,0) |
        //js.executeScript("window.scrollTo(0,0)");
        // 11 | mouseDownAt | id=main-wrapper | 1299,5.763885498046875
//        {
//            WebElement element = driver.findElement(By.id("main-wrapper"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).clickAndHold().perform();
//        }
        // 12 | mouseMoveAt | id=main-wrapper | 1299,5.763885498046875
//        {
//            WebElement element = driver.findElement(By.id("main-wrapper"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).perform();
//        }
        // 13 | mouseUpAt | id=main-wrapper | 1299,5.763885498046875
//        {
//            WebElement element = driver.findElement(By.id("main-wrapper"));
//            Actions builder = new Actions(driver);
//            builder.moveToElement(element).release().perform();
//        }
        driver.findElement(By.xpath("//table[@id='Transaction View of Manulife GSOP (US)_table']/tbody/tr[4]/td[7]/a")).click();
        //driver.findElement(By.cssSelector("#Transaction\\ View\\ of\\ Manulife\\ GSOP\\ \\(US\\)_table tr:nth-child(4) > .newReportCellStyle:nth-child(7) > .withdrawal-link")).click();
        // 14 | click | id=REALTIME |
        driver.findElement(By.id("REALTIME")).click();
        // 15 | click | id=purchase_selection_earliest |
        driver.findElement(By.id("purchase_selection_earliest")).click();
        // 16 | click | id=ee_quantity_60243648784_60243644394 |
        driver.findElement(By.id("ee_quantity_60243648784_60243644394")).click();
        // 17 | type | id=ee_quantity_60243648784_60243644394 | 5
        driver.findElement(By.id("ee_quantity_60243648784_60243644394")).sendKeys("5");
        // 18 | click | id=er_quantity_60243648784_60243644394 |
        driver.findElement(By.id("er_quantity_60243648784_60243644394")).click();
        // 19 | type | id=er_quantity_60243648784_60243644394 | 5
        driver.findElement(By.id("er_quantity_60243648784_60243644394")).sendKeys("5");
        js.executeScript("window.scrollBy(0,20)", "");
        // 20 | click | css=#tranche_plan_top_next_continue_button_div > .primaryActionButton |
        driver.findElement(By.cssSelector("#tranche_plan_top_next_continue_button_div > .primaryActionButton")).click();
        // 21 | click | css=.primaryActionButton |
        // driver.wait(10);
        //js.executeScript("window.scrollBy(0,10)", "");
        driver.findElement(By.cssSelector(".primaryActionButton")).click();
        // 22 | click | id=CASH_MAIL_TO_PARTICIPANT |
        // driver.wait(10);

        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
        WebDriverWait w = new WebDriverWait(driver, Duration.ofSeconds(4));
        //js.executeScript("window.scrollBy(0,-20)", "");
        w.until(ExpectedConditions.presenceOfElementLocated (By.cssSelector("#CASH_MAIL_TO_PARTICIPANT")));
        driver.findElement(By.cssSelector("#CASH_MAIL_TO_PARTICIPANT")).click();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        //js.executeScript("window.scrollBy(0,50)", "");
        //need wait time
        // 23 | click | id=gwt-debug-withdrawalDeliveryInstruction_nextButton |

        //driver.findElement(By.id("gwt-uid-17Label")).click();
        js.executeScript("window.scrollBy(0,300)", "");
        w.until(ExpectedConditions.presenceOfElementLocated (By.xpath("//div[6]/div[2]/button")));

        driver.findElement(By.xpath("//div[6]/div[2]/button")).click();
        //div[@id='sw-contentMain']/div[6]/div[2]/button
        //driver.findElement(By.xpath("//button[contains(.,'Continue')]")).click();
        //driver.findElement(By.xpath("//button[@id='gwt-debug-withdrawalDeliveryInstruction_nextButton']")).click();
        //driver.findElement(By.cssSelector("#gwt-debug-withdrawalDeliveryInstruction_nextButton")).click();
        //driver.findElement(By.id("gwt-debug-withdrawalDeliveryInstruction_nextButton")).click();
        // 24 | click | css=tr:nth-child(15) | wait
        //driver.wait(20);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(120));
        //w.until(ExpectedConditions.presenceOfElementLocated (By.cssSelector("tr:nth-child(15)")));
        //js.executeScript("window.scrollBy(0,200)", "");
        //driver.findElement(By.cssSelector("tr:nth-child(15)")).click();
        // 25 | click | id=confirm_transaction_button |
        js.executeScript("window.scrollBy(0,50)", "");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(120));
        js.executeScript("window.scrollBy(0,100)", "");
        w.until(ExpectedConditions.presenceOfElementLocated (By.id("confirm_transaction_button")));
        driver.findElement(By.id("confirm_transaction_button")).click();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(150));
        //js.executeScript("window.scrollBy(0,100)", "");
        w.until(ExpectedConditions.presenceOfElementLocated (By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")));
        // 26 | click | css=tr:nth-child(2) > .staticAddEditTableRightCell |
        driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).click();
        String referenceNumber = driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).getText();
        System.out.println("reference number " + referenceNumber);
        //    // 27 | click | css=tr:nth-child(2) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).click();
//    // 28 | click | css=tr:nth-child(2) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).click();
//    // 29 | click | css=tr:nth-child(3) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(3) > .staticAddEditTableRightCell")).click();
//    // 30 | click | css=tr:nth-child(3) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(3) > .staticAddEditTableRightCell")).click();
//    // 31 | click | css=tr:nth-child(3) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(3) > .staticAddEditTableRightCell")).click();
//    // 32 | click | css=tr:nth-child(2) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).click();
//    // 33 | click | css=tr:nth-child(2) > .staticAddEditTableRightCell |
//    driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).click();
        // 34 | doubleClick | css=tr:nth-child(2) > .staticAddEditTableRightCell |
        {
            WebElement element = driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        // 35 | click | css=tr:nth-child(2) > .staticAddEditTableRightCell |
        driver.findElement(By.cssSelector("tr:nth-child(2) > .staticAddEditTableRightCell")).click();
        // 36 | click | id=nav_tools |
        driver.findElement(By.id("nav_tools")).click();
        // 37 | click | linkText=Search for Transaction |
        driver.findElement(By.linkText("Search for Transaction")).click();
        // 38 | click | name=withdrawalReference |
        driver.findElement(By.name("withdrawalReference")).click();
        // 39 | type | name=withdrawalReference | referenceNumber
        driver.findElement(By.name("withdrawalReference")).sendKeys(referenceNumber);
        // 40 | click | name=action |
        driver.findElement(By.name("action")).click();
        // 41 | click | css=b:nth-child(1) |
        vars.put("window_handles", driver.getWindowHandles());
        // 42 | storeWindowHandle | root |
        driver.findElement(By.cssSelector("b:nth-child(1)")).click();
        // 43 | selectWindow | handle=${win3620} |
        vars.put("win3620", waitForWindow(2000));
        // 44 | click | name=reference_number |
        vars.put("root", driver.getWindowHandle());
        // 45 | type | name=reference_number | WRC32E1CBB8-1ER
        driver.switchTo().window(vars.get("win3620").toString());
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        // 46 | sendKeys | name=reference_number | ${KEY_ENTER}
        driver.findElement(By.name("reference_number")).click();
        // 47 | click | name=reference_number |
        driver.findElement(By.name("reference_number")).sendKeys(referenceNumber);
//        // 48 | type | name=reference_number | WRC32E1CBB8-1ER
//        driver.findElement(By.name("reference_number")).sendKeys(Keys.ENTER);
        // 49 | click | css=#cfoAction_div tr:nth-child(3) input:nth-child(1) |
        driver.findElement(By.cssSelector("#cfoAction_div tr:nth-child(3) input:nth-child(1)")).click();
//        // 50 | click | linkText=Add Fill |
//        driver.findElement(By.name("reference_number")).sendKeys(referenceNumber);
        js.executeScript("window.scrollBy(0,50)", "");

        //String quntity = driver.findElement(By.cssSelector("#cfoAction_div tr:nth-child(3) input:nth-child(1)")).getText();
        // 51 | click | name=fill_quantity |
        // 52 | type | name=fill_quantity | 10
        driver.findElement(By.linkText("Add Fill")).click();
        // 53 | click | css=tr:nth-child(30) > td:nth-child(2) |
        driver.findElement(By.name("fill_quantity")).click();
        // 54 | click | name=fill_price |
        driver.findElement(By.name("fill_quantity")).sendKeys("10");
        // 55 | type | name=fill_price | 19.75
        driver.findElement(By.cssSelector("tr:nth-child(30) > td:nth-child(2)")).click();
        String str = driver.findElement(By.cssSelector("tr:nth-child(30) > td:nth-child(2)")).getText();
        StringBuilder builder = new StringBuilder(str);
        String price = builder.substring(1, str.length() - 4).toString();
        // 56 | click | css=.defaultTextBold > input:nth-child(1) |
        driver.findElement(By.name("fill_price")).click();
        // 57 | click | css=.defaultTextBold > input:nth-child(1) |
        driver.findElement(By.name("fill_price")).sendKeys(price);
        // 58 | close |  |
        driver.findElement(By.cssSelector(".defaultTextBold > input:nth-child(1)")).click();
        // 59 | selectWindow | handle=${root} |
        driver.findElement(By.cssSelector(".defaultTextBold > input:nth-child(1)")).click();
        // 60 | click | css=.report-results-container |
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(50));
        //w.until(ExpectedConditions.presenceOfElementLocated (By.cssSelector("td > input:nth-child(2)")));
        driver.findElement(By.cssSelector("td > input:nth-child(2)")).click();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
        driver.close();
        // 61 | click | css=.newReportCellStyle:nth-child(6) |
        driver.switchTo().window(vars.get("root").toString());
        driver.quit();

        //driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        // 62 | click | css=b:nth-child(1) |
//        driver.findElement(By.cssSelector(".report-results-container")).click();
//        // 63 | selectWindow | handle=${win4231} |
//        driver.findElement(By.cssSelector(".newReportCellStyle:nth-child(6)")).click();
//        // 64 | close |  |
//        vars.put("window_handles", driver.getWindowHandles());
//        // 65 | selectWindow | handle=${root} |
//        driver.findElement(By.cssSelector("b:nth-child(1)")).click();
//        vars.put("win4231", waitForWindow(2000));
//        driver.switchTo().window(vars.get("win4231").toString());
//        driver.close();
//        driver.switchTo().window(vars.get("root").toString());
    }
}

